AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily marathon race crawler lambda

Resources:
  MarathonRaceCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: marathon-race-crawler
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Timeout: 300
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: runcalcs
      Environment:
        Variables:
          RACES_KEY: races/marathons.json
          MAX_PAGES: 80
      Events:
        DailyMidnightSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
            Enabled: true

Outputs:
  MarathonCrawlerFunctionName:
    Value: !Ref MarathonRaceCrawlerFunction
