AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily running tip generator Lambda using OpenAI

Resources:
  RunningTipsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: running-tip-of-day

  RunningTipOfDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: running-tip-of-day
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RunningTipsBucket
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutBucketCORS
                - s3:CreateBucket
              Resource: !Sub "arn:aws:s3:::${RunningTipsBucket}"
      Environment:
        Variables:
          TIPS_BUCKET: !Ref RunningTipsBucket
          TIPS_KEY_PREFIX: running-tips/tip
          OPENAI_SECRET_NAME: ChatGPTKey
          OPENAI_MODEL: gpt-4o-mini
      Events:
        DailyMidnightSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
            Enabled: true

Outputs:
  RunningTipsBucketName:
    Value: !Ref RunningTipsBucket
  RunningTipLambdaName:
    Value: !Ref RunningTipOfDayFunction
